import type { Topic } from '@/features/topics/types/topic'
import type { Article } from '@/features/articles/types/article'
import type { User, UserAccount } from '@/api/users'
import type { Interaction } from '@/features/interactions/types/interaction'
import type { ConnectionSession } from '@/features/sessions/types/session'

/**
 * Mock Topics
 */
export const MOCK_TOPICS: Array<Topic> = [
  {
    id: '1',
    name: 'Classroom Management',
    nameJa: 'クラス管理',
    description: 'Techniques for managing classroom behavior and environment',
    color: '#3b82f6',
  },
  {
    id: '2',
    name: 'Student Communication',
    nameJa: '生徒とのコミュニケーション',
    description: 'Effective ways to communicate with students',
    color: '#10b981',
  },
  {
    id: '3',
    name: 'Lesson Planning',
    nameJa: '授業準備',
    description: 'Tips for planning and preparing lessons',
    color: '#f59e0b',
  },
  {
    id: '4',
    name: 'Problem Solving',
    nameJa: '問題解決',
    description: 'Handling difficult situations in the classroom',
    color: '#ef4444',
  },
  {
    id: '5',
    name: 'Teaching Methods',
    nameJa: '教授法',
    description: 'Various teaching methodologies and approaches',
    color: '#8b5cf6',
  },
  {
    id: '6',
    name: 'Teaching Materials',
    nameJa: '教材',
    description: 'Creating and using teaching materials effectively',
    color: '#ec4899',
  },
]

/**
 * Mock Users Accounts & Users
 */
export const MOCK_USER_ACCOUNTS: Array<UserAccount> = [
  {
    id: 'user-1',
    name: '田中',
    email: 'tanaka@example.com',
    password: '123456',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'user-2',
    name: '鈴木',
    email: 'suzuki@example.com',
    password: '123456',
    createdAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: 'user-3',
    name: '山田',
    email: 'yamada@example.com',
    password: '123456',
    createdAt: new Date('2024-01-25').toISOString(),
  },
  {
    id: 'user-4',
    name: '佐藤',
    email: 'sato@example.com',
    password: '123456',
    createdAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'user-5',
    name: '小林',
    email: 'kobayashi@example.com',
    password: '123456',
    createdAt: new Date('2024-02-05').toISOString(),
  },
  {
    id: 'user-6',
    name: '伊藤',
    email: 'ito@example.com',
    password: '123456',
    createdAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'user-7',
    name: '中村',
    email: 'nakamura@example.com',
    password: '123456',
    createdAt: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'user-8',
    name: '吉田',
    email: 'yoshida@example.com',
    password: '123456',
    createdAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'user-9',
    name: '山本',
    email: 'yamamoto@example.com',
    password: '123456',
    createdAt: new Date('2024-02-25').toISOString(),
  },
  {
    id: 'user-10',
    name: '加藤',
    email: 'kato@example.com',
    password: '123456',
    createdAt: new Date('2024-03-01').toISOString(),
  },
  {
    id: 'user-11',
    name: '松本',
    email: 'matsumoto@example.com',
    password: '123456',
    createdAt: new Date('2024-03-05').toISOString(),
  },
  {
    id: 'user-12',
    name: '井上',
    email: 'inoue@example.com',
    password: '123456',
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    id: 'user-13',
    name: '木村',
    email: 'kimura@example.com',
    password: '123456',
    createdAt: new Date('2024-03-15').toISOString(),
  },
  {
    id: 'user-14',
    name: '林',
    email: 'hayashi@example.com',
    password: '123456',
    createdAt: new Date('2024-03-20').toISOString(),
  },
  {
    id: 'user-15',
    name: '清水',
    email: 'shimizu@example.com',
    password: '123456',
    createdAt: new Date('2024-03-25').toISOString(),
  },
  {
    id: 'user-16',
    name: '阿部',
    email: 'abe@example.com',
    password: '123456',
    createdAt: new Date('2024-04-01').toISOString(),
  },
  {
    id: 'user-17',
    name: '池田',
    email: 'ikeda@example.com',
    password: '123456',
    createdAt: new Date('2024-04-05').toISOString(),
  },
  {
    id: 'user-18',
    name: '橋本',
    email: 'hashimoto@example.com',
    password: '123456',
    createdAt: new Date('2024-04-10').toISOString(),
  },
  {
    id: 'user-19',
    name: '石川',
    email: 'ishikawa@example.com',
    password: '123456',
    createdAt: new Date('2024-04-15').toISOString(),
  },
  {
    id: 'user-20',
    name: '前田',
    email: 'maeda@example.com',
    password: '123456',
    createdAt: new Date('2024-04-20').toISOString(),
  },
  {
    id: 'user-21',
    name: '石川 123',
    email: 'ishikawa1451@example.com',
    password: '123456',
    createdAt: new Date('2024-04-15').toISOString(),
  },
  {
    id: 'user-22',
    name: '前田 234',
    email: 'maeda123@example.com',
    password: '123456',
    createdAt: new Date('2024-04-20').toISOString(),
  },
]

export const MOCK_USERS: Array<User> = MOCK_USER_ACCOUNTS.map(
  ({ password, ...user }) => user,
)

/**
 * Mock Articles
 */
export const MOCK_ARTICLES: Array<Article> = [
  {
    id: 'article-1',
    title: '初回授業の簡単なアイスブレイカー',
    content:
      '「2つの真実と1つの嘘」というシンプルなゲームから始めましょう。生徒は自分について2つの真実と1つの嘘を書きます。他の生徒がどれが嘘かを当てます。5分で終わり、緊張をほぐし、名前を早く覚えるのに役立ちます。',
    summary: '初回授業を始めるための5分間の簡単なアイスブレイカーゲーム',
    topicId: '1',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-01').toISOString(),
    updatedAt: new Date('2024-12-01').toISOString(),
  },
  {
    id: 'article-2',
    title: '問題行動を起こす生徒への対応',
    content:
      '生徒が授業を妨害したときは、「3-2-1」アプローチを使いましょう：3秒間のアイコンタクト、2歩近づく、1つの静かな言葉。この対立を避ける方法は、生徒を恥ずかしがらせることなく、行動を止めることがよくあります。',
    summary: '対立を避けながら問題行動に対処する優しい3-2-1メソッド',
    topicId: '1',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2024-12-02').toISOString(),
    updatedAt: new Date('2024-12-02').toISOString(),
  },
  {
    id: 'article-3',
    title: '静かな生徒との信頼関係を築く',
    content:
      '机の上に小さなメモを置きましょう：「今日は素晴らしい仕事でした！」または「あなたの思慮深い答えに気づきました。」この個人的なアプローチは、他の人の前で彼らを困らせることなく、あなたが彼らを見ていることを示します。',
    summary: '内向的な生徒とつながるためのシンプルなメモ書きテクニック',
    topicId: '2',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-03').toISOString(),
    updatedAt: new Date('2024-12-03').toISOString(),
  },
  {
    id: 'article-4',
    title: '5分間の授業ウォームアップ',
    content:
      '前回の授業からの簡単な復習問題で各授業を始めましょう。生徒が入ってくる時に黒板に書きます。最初の3つの正解には小さなシールをあげます。これにより、すぐに集中させ、前回の内容を復習できます。',
    summary: '最初から生徒を引き込むための簡単な復習問題ウォームアップ',
    topicId: '3',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-04').toISOString(),
    updatedAt: new Date('2024-12-04').toISOString(),
  },
  {
    id: 'article-5',
    title: '生徒が理解できないとき',
    content:
      '同じ説明を繰り返す代わりに、「どの部分が混乱していますか？」と尋ねましょう。これにより、正確な問題を特定できます。その後、別の例や視覚的な補助を使います。多くの場合、問題はすべてではなく、1つの特定の概念です。',
    summary: '特定の混乱を特定して解決するための質問ベースのアプローチ',
    topicId: '4',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2024-12-05').toISOString(),
    updatedAt: new Date('2024-12-05').toISOString(),
  },
  {
    id: 'article-6',
    title: '実物を使った授業',
    content:
      '授業に関連する日常的なアイテムを持参しましょう。色を教える？実際の果物を見せます。数字を教える？硬貨やボタンを使います。生徒は写真だけでなく、実際の物に触れて見ることができると、よりよく覚えます。',
    summary: 'より良い記憶定着のために写真の代わりに実物を使用する',
    topicId: '6',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-06').toISOString(),
    updatedAt: new Date('2024-12-06').toISOString(),
  },
  {
    id: 'article-7',
    title: 'グループワークを簡単に',
    content:
      '役割を割り当てましょう：リーダー（グループをタスクに集中させる）、ライター（メモを取る）、プレゼンター（結果を共有する）、タイムキーパー（時計を見る）。この構造により、1人がすべての作業を行うことを防ぎ、全員を参加させます。',
    summary: '効果的なグループワークのための役割分担戦略',
    topicId: '5',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-07').toISOString(),
    updatedAt: new Date('2024-12-07').toISOString(),
  },
  {
    id: 'article-8',
    title: '簡単なエグジットチケット方法',
    content:
      '付箋で授業を終えましょう。生徒は学んだこと1つと、まだ持っている質問1つを書きます。退出時に集めます。次の授業の前に確認して、共通の質問に対処し、何が定着したかを見ます。',
    summary: '理解を確認し、次の授業を計画するための付箋エグジットチケット',
    topicId: '3',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2024-12-08').toISOString(),
    updatedAt: new Date('2024-12-08').toISOString(),
  },
  {
    id: 'article-9',
    title: '宿題の提出率を上げる',
    content:
      '宿題を提出した生徒をクラスの前で褒めるのではなく、個別にスタンプや短いコメントを返しましょう。提出しなかった生徒には、放課後にサポートする時間を設けることで、「罰」ではなく「支援」としてアプローチします。',
    summary: 'ポジティブな強化とサポートで宿題提出を促す',
    topicId: '1',
    authorId: 'user-1',
    readTime: 2,
    createdAt: new Date('2024-12-09').toISOString(),
    updatedAt: new Date('2024-12-09').toISOString(),
  },
  {
    id: 'article-10',
    title: '居眠りする生徒への対応',
    content:
      '大声で起こすのは避けましょう。机を軽く叩くか、近くに行って静かに名前を呼びます。授業後に「疲れているの？」と体調を気遣うことで、信頼関係を崩さずに指導できます。',
    summary: '生徒の尊厳を守りつつ居眠りに対処する方法',
    topicId: '2',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2024-12-10').toISOString(),
    updatedAt: new Date('2024-12-10').toISOString(),
  },
  {
    id: 'article-11',
    title: '効果的な板書計画',
    content:
      '黒板を3分割して使いましょう。左は「今日の目標と復習」、中央は「メインの学習内容」、右は「まとめと宿題」。消す頻度を減らすことで、ノートを取るのが遅い生徒も追いつけます。',
    summary: '視覚的に整理された3分割板書法',
    topicId: '3',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-11').toISOString(),
    updatedAt: new Date('2024-12-11').toISOString(),
  },
  {
    id: 'article-12',
    title: '発言を促す「待つ時間」',
    content:
      '質問をした後、すぐに指名せず、最低3〜5秒待ちましょう。この沈黙は、考えるのが遅い生徒にチャンスを与え、回答の質を高めます。「シンクタイム」と名付けて生徒に周知するのも効果的です。',
    summary: '回答の質を高めるための3〜5秒の待機時間',
    topicId: '4',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-12').toISOString(),
    updatedAt: new Date('2024-12-12').toISOString(),
  },
  {
    id: 'article-13',
    title: '早く課題が終わった生徒へ',
    content:
      '「アンカータスク」を用意しましょう。読書、クロスワードパズル、または次の単元の予習など、静かに一人でできる活動リストを作成し、早く終わった生徒が手持ち無沙汰にならないようにします。',
    summary: '空き時間を有効活用するアンカータスクの導入',
    topicId: '1',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2024-12-13').toISOString(),
    updatedAt: new Date('2024-12-13').toISOString(),
  },
  {
    id: 'article-14',
    title: 'ピア・ティーチングの効果',
    content:
      '「隣の人に今の説明を1分で教えてみて」と促します。教えることは学ぶことの最良の方法です。生徒同士が教え合うことで、理解度が深まり、教室の雰囲気も活発になります。',
    summary: '生徒同士で教え合い理解を深めるテクニック',
    topicId: '5',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-14').toISOString(),
    updatedAt: new Date('2024-12-14').toISOString(),
  },
  {
    id: 'article-15',
    title: '授業中の「移動」を取り入れる',
    content:
      '長時間座っていると集中力が切れます。「賛成の人は右、反対の人は左に移動して」など、物理的な動きを伴うアクティビティを取り入れることで、脳を活性化させます。',
    summary: '脳を活性化させるための教室内の移動戦略',
    topicId: '6',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-15').toISOString(),
    updatedAt: new Date('2024-12-15').toISOString(),
  },
  {
    id: 'article-16',
    title: '効果的な褒め言葉',
    content:
      '「頭がいいね」ではなく「よく努力したね」「その解き方は工夫されているね」とプロセスを褒めましょう。成長マインドセットを育み、次への意欲につなげます。',
    summary: '結果ではなくプロセスを重視した褒め方',
    topicId: '2',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2024-12-16').toISOString(),
    updatedAt: new Date('2024-12-16').toISOString(),
  },
  {
    id: 'article-17',
    title: '授業終わりの片付けルーチン',
    content:
      'チャイムが鳴る2分前に音楽をかけ、「音楽が止まるまでに片付けと整列を完了させる」ゲームにします。楽しみながら掃除や整理整頓の習慣を身につけさせます。',
    summary: '音楽を使った楽しい片付けと終了のルーチン',
    topicId: '1',
    authorId: 'user-3',
    readTime: 1,
    createdAt: new Date('2024-12-17').toISOString(),
    updatedAt: new Date('2024-12-17').toISOString(),
  },
  {
    id: 'article-18',
    title: '保護者へのポジティブな連絡',
    content:
      '問題が起きた時だけ電話するのではなく、生徒が良いことをした時に保護者にメールや電話をしましょう。「今日、〇〇さんは友達を助けてくれました」という報告は、家庭との信頼関係を劇的に改善します。',
    summary: '信頼残高を増やすための良いニュースの共有',
    topicId: '2',
    authorId: 'user-1',
    readTime: 2,
    createdAt: new Date('2024-12-18').toISOString(),
    updatedAt: new Date('2024-12-18').toISOString(),
  },
  {
    id: 'article-19',
    title: 'ランダム指名の工夫',
    content:
      'アイスキャンディーの棒に生徒の名前を書き、瓶から引いて指名します。公平性を保ち、いつ指されるかわからない適度な緊張感を維持できます。引いた棒は別の瓶に移し、全員が当たるようにします。',
    summary: 'アイスの棒を使った公平なランダム指名法',
    topicId: '3',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2024-12-19').toISOString(),
    updatedAt: new Date('2024-12-19').toISOString(),
  },
  {
    id: 'article-20',
    title: 'テスト前の不安解消',
    content:
      'テスト開始の5分前に、不安な気持ちを紙に書き出させ、それをくしゃくしゃにして捨てさせます。心理学的に、不安を物理的に捨てることでパフォーマンスが向上することが示されています。',
    summary: '筆記開示を利用したテストの緊張緩和法',
    topicId: '2',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-20').toISOString(),
    updatedAt: new Date('2024-12-20').toISOString(),
  },
  {
    id: 'article-21',
    title: 'ハンドサインで理解度確認',
    content:
      '「わかったら親指を上、少し不安なら横、わからないなら下」というジェスチャーを使います。声を出さずに全員の理解度を一瞬で把握でき、授業のペース調整に役立ちます。',
    summary: '素早いフィードバックのためのハンドサイン活用',
    topicId: '4',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-21').toISOString(),
    updatedAt: new Date('2024-12-21').toISOString(),
  },
  {
    id: 'article-22',
    title: '声のトーンを使い分ける',
    content:
      '重要なポイントを話すときは、逆に声を小さくしてみましょう。生徒は聞き取ろうとして静かになり、集中します。常に大きな声を出すよりも効果的です。',
    summary: '注目を集めるための「ウィスパーボイス」テクニック',
    topicId: '3',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2024-12-22').toISOString(),
    updatedAt: new Date('2024-12-22').toISOString(),
  },
  {
    id: 'article-23',
    title: '間違いを歓迎する文化',
    content:
      '「間違いは脳が成長している証拠です」と繰り返し伝えましょう。教師自身もわざと間違えて見せ、訂正する姿を見せることで、失敗を恐れない環境を作ります。',
    summary: '失敗を学習の機会として捉え直す教室文化',
    topicId: '2',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-23').toISOString(),
    updatedAt: new Date('2024-12-23').toISOString(),
  },
  {
    id: 'article-24',
    title: 'ゲストスピーカーの活用',
    content:
      '地域の人や他の先生を5分だけ招いて、専門分野について話してもらいましょう。いつもと違う大人の話は、生徒の興味を惹きつけ、授業に新鮮な風を吹き込みます。',
    summary: '外部の視点を取り入れて授業を活性化する',
    topicId: '6',
    authorId: 'user-1',
    readTime: 2,
    createdAt: new Date('2024-12-24').toISOString(),
    updatedAt: new Date('2024-12-24').toISOString(),
  },
  {
    id: 'article-25',
    title: '付箋ブレインストーミング',
    content:
      'グループワークの際、まずは個人で付箋にアイデアを書き、その後模造紙に貼って整理します。声の大きい生徒だけでなく、全員の意見が可視化される公平な方法です。',
    summary: '全員参加を保証する付箋を使ったアイデア出し',
    topicId: '5',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2024-12-25').toISOString(),
    updatedAt: new Date('2024-12-25').toISOString(),
  },
  {
    id: 'article-26',
    title: '授業の「予告編」を作る',
    content:
      '次回の授業のトピックについて、興味深い写真や謎めいた質問を授業の最後に提示します。「来週はこの謎を解きます」と言うことで、次の授業への期待感を高めます。',
    summary: '生徒の好奇心を刺激する次回予告のテクニック',
    topicId: '3',
    authorId: 'user-3',
    readTime: 1,
    createdAt: new Date('2024-12-26').toISOString(),
    updatedAt: new Date('2024-12-26').toISOString(),
  },
  {
    id: 'article-27',
    title: '自己評価シートの活用',
    content:
      '学期の中間で、生徒自身に「得意なこと」と「改善したいこと」を評価させます。教師の評価と比較することで、メタ認知能力（自分を客観視する力）を育てます。',
    summary: 'メタ認知を育てるための中間自己評価',
    topicId: '4',
    authorId: 'user-1',
    readTime: 2,
    createdAt: new Date('2024-12-27').toISOString(),
    updatedAt: new Date('2024-12-27').toISOString(),
  },
  {
    id: 'article-28',
    title: '座席配置の戦略',
    content:
      'U字型の配置はディスカッションに、列ごとの配置はテストや講義に適しています。活動内容に合わせて机の配置を変えるだけで、生徒のモードを切り替えることができます。',
    summary: '学習目的に合わせた効果的な座席レイアウト',
    topicId: '1',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2024-12-28').toISOString(),
    updatedAt: new Date('2024-12-28').toISOString(),
  },
  {
    id: 'article-29',
    title: 'ストーリーテリングの力',
    content:
      '歴史や科学の事実を教える際、それを物語として語りましょう。「100年前、ある発明家が...」と始めることで、単なる暗記が感情を伴う記憶に変わります。',
    summary: '記憶定着を助ける物語調の解説法',
    topicId: '6',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2024-12-29').toISOString(),
    updatedAt: new Date('2024-12-29').toISOString(),
  },
  {
    id: 'article-30',
    title: 'タイマーの視覚化',
    content:
      '残り時間を口で言うだけでなく、大きなデジタルタイマーや砂時計を黒板の前に置きます。時間の経過を可視化することで、生徒のタイムマネジメント能力が向上します。',
    summary: '作業効率を上げるための視覚的タイマー活用',
    topicId: '1',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2024-12-30').toISOString(),
    updatedAt: new Date('2024-12-30').toISOString(),
  },
  {
    id: 'article-31',
    title: '「なぜ？」を5回繰り返す',
    content:
      '深い理解を促すために、生徒の答えに対して「それはなぜ？」と掘り下げます。表面的な知識だけでなく、根本的な原理まで考えさせるクリティカルシンキングの練習です。',
    summary: '思考を深めるための「なぜ」の連鎖質問',
    topicId: '4',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2025-01-01').toISOString(),
    updatedAt: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'article-32',
    title: 'デジタルデトックスの時間',
    content:
      '授業の一部を完全にアナログにします。紙と鉛筆だけを使う時間を設けることで、通知や画面の光から離れ、深い集中と思索の時間を確保します。',
    summary: '集中力を取り戻すための完全アナログ時間',
    topicId: '1',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2025-01-02').toISOString(),
    updatedAt: new Date('2025-01-02').toISOString(),
  },
  {
    id: 'article-33',
    title: '教室の環境整備',
    content:
      '掲示物が多すぎると気が散る原因になります。生徒の作品や重要なルールだけを残し、定期的に整理しましょう。シンプルな壁面は集中力を高めます。',
    summary: '視覚的ノイズを減らす教室環境の整理',
    topicId: '1',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2025-01-03').toISOString(),
    updatedAt: new Date('2025-01-03').toISOString(),
  },
  {
    id: 'article-34',
    title: '教師のリフレクション',
    content:
      '授業後、1行だけでいいので日記をつけましょう。「うまくいったこと」と「変えるべきこと」。この積み重ねが、翌年の授業計画を劇的に楽にします。',
    summary: '授業改善のための1行教師日記',
    topicId: '3',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2025-01-04').toISOString(),
    updatedAt: new Date('2025-01-04').toISOString(),
  },
  {
    id: 'article-35',
    title: '選択肢を与える',
    content:
      '宿題を出す際、「エッセイを書く」か「ポスターを作る」か選ばせます。学習目標は同じでも、表現方法を選べるようにすることで、生徒の主体性を引き出します。',
    summary: '自律性を高めるための課題選択制',
    topicId: '5',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2025-01-05').toISOString(),
    updatedAt: new Date('2025-01-05').toISOString(),
  },
  {
    id: 'article-36',
    title: '名前を覚えるゲーム',
    content:
      '新学期には、名前の頭文字を使った形容詞をつけるゲームをします（例：明るいアキコ、元気なゲン）。リズムに合わせて繰り返すことで、全員が楽しみながら名前を覚えられます。',
    summary: 'クラスの絆を深めるネームゲーム',
    topicId: '1',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2025-01-06').toISOString(),
    updatedAt: new Date('2025-01-06').toISOString(),
  },
  {
    id: 'article-37',
    title: '静寂の活用',
    content:
      '授業中に1分間の「完全な沈黙」を作ります。その間、学んだことを脳内で整理させます。常に情報を浴び続けるのではなく、情報を定着させるための空白の時間です。',
    summary: '情報整理のための意図的な沈黙タイム',
    topicId: '3',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2025-01-07').toISOString(),
    updatedAt: new Date('2025-01-07').toISOString(),
  },
  {
    id: 'article-38',
    title: '「わからない」と言える勇気',
    content:
      '教師も答えられない質問には正直に「わからないから、一緒に調べよう」と言いましょう。知的な謙虚さを示すことは、知ったかぶりをするよりも生徒の尊敬を集めます。',
    summary: '教師の誠実さが生徒の信頼を生む',
    topicId: '2',
    authorId: 'user-3',
    readTime: 1,
    createdAt: new Date('2025-01-08').toISOString(),
    updatedAt: new Date('2025-01-08').toISOString(),
  },
  {
    id: 'article-39',
    title: '授業開始の音楽',
    content:
      '授業開始時に決まった穏やかな音楽を流します。これが「学習モードへの切り替えスイッチ」となり、チャイムが鳴る頃には生徒が落ち着いて着席するようになります。',
    summary: '学習モードへの移行を促す音楽の活用',
    topicId: '1',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2025-01-09').toISOString(),
    updatedAt: new Date('2025-01-09').toISOString(),
  },
  {
    id: 'article-40',
    title: 'ペアでのチェック',
    content:
      '提出物を出す前に、隣の人と交換してチェックさせます。名前は書いてあるか？答えは全て埋まっているか？単純なミスを減らし、教師の確認作業を減らすことができます。',
    summary: '提出物の不備を減らすペアチェック',
    topicId: '5',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-01-10').toISOString(),
  },
  {
    id: 'article-41',
    title: '具体物がない時の比喩',
    content:
      '抽象的な概念を教える時は、身近なものに例えましょう。電気回路を「水の流れ」、細胞を「工場」に例えるなど、既知のイメージを使うことで理解を助けます。',
    summary: '抽象的な概念を理解させる比喩の技術',
    topicId: '6',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2025-01-11').toISOString(),
    updatedAt: new Date('2025-01-11').toISOString(),
  },
  {
    id: 'article-42',
    title: '感情のチェックイン',
    content:
      '朝の会で、今の気分を天気（晴れ、曇り、雨）で表現させます。生徒の精神状態を把握でき、雨（不調）の生徒にはその日、特に配慮して接することができます。',
    summary: '生徒のメンタル状態を把握する天気メタファー',
    topicId: '2',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2025-01-12').toISOString(),
    updatedAt: new Date('2025-01-12').toISOString(),
  },
  {
    id: 'article-43',
    title: 'ノート指導の基本',
    content:
      '「板書を写す」だけでなく、右側に「自分の考えや疑問」を書くスペースを作らせます。情報の記録だけでなく、情報の処理をノート上で行わせるためです。',
    summary: '思考力を高めるコーネル式ノートの簡易版',
    topicId: '3',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2025-01-13').toISOString(),
    updatedAt: new Date('2025-01-13').toISOString(),
  },
  {
    id: 'article-44',
    title: 'ディベートの導入',
    content:
      '正解のない問いについて、あえて立場を決めて議論させます。自分の意見とは異なる立場を擁護することで、多角的な視点と論理的思考力が養われます。',
    summary: '多角的な視点を育てるミニディベート',
    topicId: '5',
    authorId: 'user-3',
    readTime: 2,
    createdAt: new Date('2025-01-14').toISOString(),
    updatedAt: new Date('2025-01-14').toISOString(),
  },
  {
    id: 'article-45',
    title: '質問ボックスの設置',
    content:
      '教室の後ろに箱を置き、授業中に聞けなかった質問を匿名で入れさせます。恥ずかしがり屋の生徒の声を拾い上げ、次の授業で解説することで安心感を与えます。',
    summary: '内気な生徒の質問を拾う匿名ボックス',
    topicId: '2',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2025-01-15').toISOString(),
    updatedAt: new Date('2025-01-15').toISOString(),
  },
  {
    id: 'article-46',
    title: '動画教材の適切な長さ',
    content:
      '授業で動画を使う際は、5分以内に留めましょう。それ以上は受動的になりがちです。動画の途中で止めて質問を投げかけ、能動的な視聴を促すことが重要です。',
    summary: '集中力を維持する動画教材の活用ルール',
    topicId: '6',
    authorId: 'user-2',
    readTime: 2,
    createdAt: new Date('2025-01-16').toISOString(),
    updatedAt: new Date('2025-01-16').toISOString(),
  },
  {
    id: 'article-47',
    title: '良い行動のモデル化',
    content:
      '口で説明するより、やって見せましょう。「静かに本を開く」とはどういうことか、教師が大げさに実演します。視覚的なモデルは、言葉よりも早く伝わります。',
    summary: '言葉より伝わる教師のモデリング',
    topicId: '1',
    authorId: 'user-3',
    readTime: 1,
    createdAt: new Date('2025-01-17').toISOString(),
    updatedAt: new Date('2025-01-17').toISOString(),
  },
  {
    id: 'article-48',
    title: '授業の「余白」',
    content:
      '授業計画を詰め込みすぎないようにしましょう。予期せぬ質問や興味深い議論のために、5分程度の予備時間を確保しておくと、焦らず柔軟に対応できます。',
    summary: '柔軟な授業のための意図的な余白時間',
    topicId: '3',
    authorId: 'user-1',
    readTime: 1,
    createdAt: new Date('2025-01-18').toISOString(),
    updatedAt: new Date('2025-01-18').toISOString(),
  },
  {
    id: 'article-49',
    title: 'サンキューカード',
    content:
      '学期末に、生徒同士でお互いの良かったところをカードに書いて交換します。クラス内の肯定的な関係性を確認し、自己肯定感を高めて学期を終えられます。',
    summary: '感謝と承認で締めくくる学期末のアクティビティ',
    topicId: '2',
    authorId: 'user-2',
    readTime: 1,
    createdAt: new Date('2025-01-19').toISOString(),
    updatedAt: new Date('2025-01-19').toISOString(),
  },
  {
    id: 'article-50',
    title: '次のステップへ',
    content:
      '授業の最後に、「今日学んだことを家でどう使えるか？」と問いかけます。学校での学びと実生活を結びつけることで、学習の意義を再確認させます。',
    summary: '学びを実生活に接続するクロージング',
    topicId: '4',
    authorId: 'user-3',
    readTime: 1,
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date('2025-01-20').toISOString(),
  },
]

/**
 * Mock Interactions
 */
export const MOCK_INTERACTIONS: Array<Interaction> = [
  {
    id: 'interaction-1',
    articleId: 'article-1',
    userId: 'user-2',
    type: 'useful',
    createdAt: new Date('2024-12-01T10:00:00').toISOString(),
  },
  {
    id: 'interaction-2',
    articleId: 'article-1',
    userId: 'user-3',
    type: 'useful',
    createdAt: new Date('2024-12-01T11:00:00').toISOString(),
  },
  {
    id: 'interaction-3',
    articleId: 'article-1',
    userId: 'user-1',
    type: 'comment',
    content: '昨日試してみましたが、完璧に機能しました！',
    createdAt: new Date('2024-12-01T12:00:00').toISOString(),
  },
  {
    id: 'interaction-4',
    articleId: 'article-2',
    userId: 'user-1',
    type: 'useful',
    createdAt: new Date('2024-12-02T09:00:00').toISOString(),
  },
  {
    id: 'interaction-5',
    articleId: 'article-2',
    userId: 'user-3',
    type: 'useful',
    createdAt: new Date('2024-12-02T10:00:00').toISOString(),
  },
  {
    id: 'interaction-6',
    articleId: 'article-2',
    userId: 'user-2',
    type: 'comment',
    content: 'この方法は声を上げるよりもずっと良いです。',
    createdAt: new Date('2024-12-02T11:00:00').toISOString(),
  },
  {
    id: 'interaction-7',
    articleId: 'article-3',
    userId: 'user-2',
    type: 'useful',
    createdAt: new Date('2024-12-03T14:00:00').toISOString(),
  },
  {
    id: 'interaction-8',
    articleId: 'article-4',
    userId: 'user-1',
    type: 'useful',
    createdAt: new Date('2024-12-04T08:00:00').toISOString(),
  },
  {
    id: 'interaction-9',
    articleId: 'article-4',
    userId: 'user-2',
    type: 'useful',
    createdAt: new Date('2024-12-04T09:00:00').toISOString(),
  },
  {
    id: 'interaction-10',
    articleId: 'article-4',
    userId: 'user-3',
    type: 'useful',
    createdAt: new Date('2024-12-04T10:00:00').toISOString(),
  },
  {
    id: 'interaction-11',
    articleId: 'article-1',
    userId: 'user-4',
    type: 'useful',
    createdAt: new Date('2024-12-01T13:00:00').toISOString(),
  },
  {
    id: 'interaction-12',
    articleId: 'article-1',
    userId: 'user-5',
    type: 'useful',
    createdAt: new Date('2024-12-01T13:30:00').toISOString(),
  },
  {
    id: 'interaction-13',
    articleId: 'article-1',
    userId: 'user-6',
    type: 'useful',
    createdAt: new Date('2024-12-01T14:00:00').toISOString(),
  },
  {
    id: 'interaction-14',
    articleId: 'article-1',
    userId: 'user-7',
    type: 'useful',
    createdAt: new Date('2024-12-01T14:30:00').toISOString(),
  },
  {
    id: 'interaction-15',
    articleId: 'article-1',
    userId: 'user-8',
    type: 'useful',
    createdAt: new Date('2024-12-01T15:00:00').toISOString(),
  },
  {
    id: 'interaction-16',
    articleId: 'article-1',
    userId: 'user-9',
    type: 'useful',
    createdAt: new Date('2024-12-01T15:30:00').toISOString(),
  },
  {
    id: 'interaction-17',
    articleId: 'article-1',
    userId: 'user-10',
    type: 'useful',
    createdAt: new Date('2024-12-01T16:00:00').toISOString(),
  },
  {
    id: 'interaction-18',
    articleId: 'article-1',
    userId: 'user-11',
    type: 'useful',
    createdAt: new Date('2024-12-01T16:30:00').toISOString(),
  },
  {
    id: 'interaction-19',
    articleId: 'article-1',
    userId: 'user-12',
    type: 'useful',
    createdAt: new Date('2024-12-01T17:00:00').toISOString(),
  },
  {
    id: 'interaction-20',
    articleId: 'article-1',
    userId: 'user-13',
    type: 'useful',
    createdAt: new Date('2024-12-01T17:30:00').toISOString(),
  },
  {
    id: 'interaction-21',
    articleId: 'article-1',
    userId: 'user-14',
    type: 'useful',
    createdAt: new Date('2024-12-01T18:00:00').toISOString(),
  },
  {
    id: 'interaction-22',
    articleId: 'article-1',
    userId: 'user-15',
    type: 'useful',
    createdAt: new Date('2024-12-01T18:30:00').toISOString(),
  },
  {
    id: 'interaction-23',
    articleId: 'article-1',
    userId: 'user-16',
    type: 'useful',
    createdAt: new Date('2024-12-01T19:00:00').toISOString(),
  },
  {
    id: 'interaction-24',
    articleId: 'article-1',
    userId: 'user-17',
    type: 'useful',
    createdAt: new Date('2024-12-01T19:30:00').toISOString(),
  },
  {
    id: 'interaction-25',
    articleId: 'article-1',
    userId: 'user-18',
    type: 'useful',
    createdAt: new Date('2024-12-01T20:00:00').toISOString(),
  },
  {
    id: 'interaction-26',
    articleId: 'article-1',
    userId: 'user-19',
    type: 'useful',
    createdAt: new Date('2024-12-01T20:30:00').toISOString(),
  },
  {
    id: 'interaction-27',
    articleId: 'article-1',
    userId: 'user-20',
    type: 'useful',
    createdAt: new Date('2024-12-01T21:00:00').toISOString(),
  },
  {
    id: 'interaction-28',
    articleId: 'article-1',
    userId: 'user-21',
    type: 'useful',
    createdAt: new Date('2024-12-01T21:30:00').toISOString(),
  },
  {
    id: 'interaction-29',
    articleId: 'article-1',
    userId: 'user-22',
    type: 'useful',
    createdAt: new Date('2024-12-01T22:00:00').toISOString(),
  },
  {
    id: 'interaction-30',
    articleId: 'article-2',
    userId: 'user-4',
    type: 'useful',
    createdAt: new Date('2024-12-02T12:00:00').toISOString(),
  },
  {
    id: 'interaction-31',
    articleId: 'article-2',
    userId: 'user-5',
    type: 'useful',
    createdAt: new Date('2024-12-02T12:30:00').toISOString(),
  },
  {
    id: 'interaction-32',
    articleId: 'article-2',
    userId: 'user-6',
    type: 'useful',
    createdAt: new Date('2024-12-02T13:00:00').toISOString(),
  },
  {
    id: 'interaction-33',
    articleId: 'article-2',
    userId: 'user-7',
    type: 'useful',
    createdAt: new Date('2024-12-02T13:30:00').toISOString(),
  },
  {
    id: 'interaction-34',
    articleId: 'article-2',
    userId: 'user-8',
    type: 'useful',
    createdAt: new Date('2024-12-02T14:00:00').toISOString(),
  },
  {
    id: 'interaction-35',
    articleId: 'article-2',
    userId: 'user-9',
    type: 'useful',
    createdAt: new Date('2024-12-02T14:30:00').toISOString(),
  },
  {
    id: 'interaction-36',
    articleId: 'article-2',
    userId: 'user-10',
    type: 'useful',
    createdAt: new Date('2024-12-02T15:00:00').toISOString(),
  },
  {
    id: 'interaction-37',
    articleId: 'article-2',
    userId: 'user-11',
    type: 'useful',
    createdAt: new Date('2024-12-02T15:30:00').toISOString(),
  },
  {
    id: 'interaction-38',
    articleId: 'article-2',
    userId: 'user-12',
    type: 'useful',
    createdAt: new Date('2024-12-02T16:00:00').toISOString(),
  },
  {
    id: 'interaction-39',
    articleId: 'article-2',
    userId: 'user-13',
    type: 'useful',
    createdAt: new Date('2024-12-02T16:30:00').toISOString(),
  },
  {
    id: 'interaction-40',
    articleId: 'article-2',
    userId: 'user-14',
    type: 'useful',
    createdAt: new Date('2024-12-02T17:00:00').toISOString(),
  },
  {
    id: 'interaction-41',
    articleId: 'article-2',
    userId: 'user-15',
    type: 'useful',
    createdAt: new Date('2024-12-02T17:30:00').toISOString(),
  },
  {
    id: 'interaction-42',
    articleId: 'article-2',
    userId: 'user-16',
    type: 'useful',
    createdAt: new Date('2024-12-02T18:00:00').toISOString(),
  },
  {
    id: 'interaction-43',
    articleId: 'article-2',
    userId: 'user-17',
    type: 'useful',
    createdAt: new Date('2024-12-02T18:30:00').toISOString(),
  },
  {
    id: 'interaction-44',
    articleId: 'article-2',
    userId: 'user-18',
    type: 'useful',
    createdAt: new Date('2024-12-02T19:00:00').toISOString(),
  },
  {
    id: 'interaction-45',
    articleId: 'article-2',
    userId: 'user-19',
    type: 'useful',
    createdAt: new Date('2024-12-02T19:30:00').toISOString(),
  },
  {
    id: 'interaction-46',
    articleId: 'article-2',
    userId: 'user-20',
    type: 'useful',
    createdAt: new Date('2024-12-02T20:00:00').toISOString(),
  },
  {
    id: 'interaction-47',
    articleId: 'article-2',
    userId: 'user-21',
    type: 'useful',
    createdAt: new Date('2024-12-02T20:30:00').toISOString(),
  },
  {
    id: 'interaction-48',
    articleId: 'article-2',
    userId: 'user-22',
    type: 'useful',
    createdAt: new Date('2024-12-02T21:00:00').toISOString(),
  },
  {
    id: 'interaction-49',
    articleId: 'article-2',
    userId: 'user-23',
    type: 'useful',
    createdAt: new Date('2024-12-02T21:30:00').toISOString(),
  },
]

/**
 * Mock Sessions (empty initially, will be created when articles reach threshold)
 */
export const MOCK_SESSIONS: Array<ConnectionSession> = [
  {
    id: 'session-1',
    articleId: 'article-1',
    topicId: '1',
    title: '記事内容についてディスカッション',
    description: 'この記事の内容を深掘りし、意見交換を行うセッションです。',
    goal: '知見共有・理解深化',
    status: 'open',
    participantIds: ['user-22'],
    participantInfoMap: {
      'user-22': {
        email: 'maeda123@example.com',
        note: '記事の内容に非常に興味があります。',
      },
    },
    minParticipants: 3,
    createdAt: new Date().toISOString(),
    expiresAt: new Date(
      Date.now() + 1000 * 60 * 60 * 24, // +1 ngày
    ).toISOString(),
    hostId: 'user-1',
    time: new Date(
      Date.now() + 1000 * 60 * 60 * 48, // +2 ngày
    ).toISOString(),
  },
]
